### ISSUE TITLE
分かりやすい

### ISSUE THREAD

**Issue by c0a2108975** [c0a21099/ProjExD#10]
https://github.com/c0a21099/ProjExD/blob/bd2879e2b2e29e84b37de388b8aff8b6af66296e/ex05/fight_kokaton.py#L113

コメントアウトがなかの定義の核心をついていて理解を促す努力ができていると思った

**Comment by nissy-code** [comment]
ありがとうございます. わかりやすく読みやすいコードを目指して頑張ります.
