### ISSUE TITLE
いい変数名だと思います

### ISSUE THREAD

**Issue by c0a2108975** [c0a21099/ProjExD#2]
https://github.com/c0a21099/ProjExD/blob/3a1da75ebe645adbea6ae55e7dfc3529268eb4a1/ex01/alphabet.py#L6

いい変数名だともいます

**Comment by c0a21099** [comment]
ありがとうございます. 特にコードの修正はしません.

**Comment by c0a21099** [comment]
ありがとうございます. 特にコードの修正はしません.

**Comment by nissy-code** [comment]
ありがとうございます! pythonに変数名褒められたとコメントアウトしておきました!
