### ISSUE TITLE
関数の上にその関数についての説明が書いてあり、コードが読みやすい

### ISSUE THREAD

**Issue by c0a2108975** [c0a21099/ProjExD#4]
https://github.com/c0a21099/ProjExD/blob/23ba42251f82466cc330fd28e6a408be2a0b7e45/ex02/calc.py#L5

関数の上にその関数についての説明が書いてあり、コードが読みやすい

**Comment by nissy-code** [comment]
ありがとうございます!!
読みやすいコードを目指して普段から頑張ります!!
