### ISSUE TITLE
if文の書き方

### ISSUE THREAD

**Issue by c0a2108975** [c0a21099/ProjExD#6]
https://github.com/c0a21099/ProjExD/blob/b274217b100b3467bd1d3ee6551dffa13a4cd081/ex03/maze.py#L34-L43

if文の処理の仕方を一行にまとめることで行がスッキリして見えてとても見やすかった

**Comment by nissy-code** [comment]
私自身も感じていましたが, コードを治す余裕もなく, 
またリスト等でまとめたとしてプログラムが動かなくなると困ると思い, 今回は見送りました.

次回以降改善できるようにしていきたいです.
