### ISSUE TITLE
clock

### ISSUE THREAD

**Issue by c0a2103528** [c0a21099/ProjExD#7]
https://github.com/c0a21099/ProjExD/blob/b383b6ff8a05ccef93ae0d99ad3595423c23a5ab/ex04/dodge_bomb.py#L12
pg.time.clockについて、「clock」ではなく「Clock」でないとエラーが発生する

**Comment by nissy-code** [comment]
ご指摘ありがとうございます. 完全に見過ごしてました.
修正したのでご確認下さい.
