### ISSUE TITLE
ネストがふかい

### ISSUE THREAD

**Issue by c0a2108975** [c0a21099/ProjExD#8]
https://github.com/c0a21099/ProjExD/blob/b383b6ff8a05ccef93ae0d99ad3595423c23a5ab/ex04/dodge_bomb.py#L90

ネストが深いのでちょっと読みずらかった

**Comment by nissy-code** [comment]
講義内で読みやすいコードにしろということだったので, 読みやすくしたつもりですがうまく伝わらなかった模様ですみませんでした.

修正したいところですが, 技量が乏しくこれ以外の代替の書き方を思いつかなかったので今回は見送らせて下さい.
