### ISSUE TITLE
説明の追加

### ISSUE THREAD

**Issue by c0a211211d** [c0a21099/ProjExD#9]
https://github.com/c0a21099/ProjExD/blob/bd2879e2b2e29e84b37de388b8aff8b6af66296e/ex05/fight_kokaton.py#L6-L8
この部分がどのようなものなのかわかりにくいため、説明文を追加した方がいいと思う

**Comment by nissy-code** [comment]
ご指摘ありがとうございます.
コメントアウトを追加しました.
